### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [mrduke44/colmar#5]
(Exceeds Expectations)

Well done on this project! It looks like you have a solid understanding of the display and positioning of elements on a page. Keep up the good work on proper formatting of code and great job handling display on mobile devices! The hover effects are also a nice addition that helps improve user experience!

One thing you could consider for next time is using `id`s for the main sections of your page (#4). In addition to being able to serve as selectors for styling your elements, (like `class`es), `id`s would also allow you to create hyperlinks to jump to that specific part of the page. Here is a good resource on this: http://www.turnwall.com/articles/basic-styling-with-css-class-id/ 

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Happy coding!

**Comment by mrduke44** [comment]
Did build this after that project http://light-metals.com/ :)
